In [108]:
import pandas as pd

In [109]:
# 1. Считайте датасет из файла train.csv (это данные о выживаемости на Титанике) - 1 балл
df = pd.read_csv('/content/titanic (1).csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [110]:
# 2.Выведите основную информацию о датасете: информацию о типах данных, число пропусков, средние значения и т.д. - 1 балл

#  описание статистик полей
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [111]:
# общая инфа о датафрейме
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [112]:
# колво пропусков
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [113]:
# 3. Посчитайте процент выживаемости у каждого класса пассажиров (Pclass) - 1 балл
df.groupby('Pclass').agg(survived_mean = ('Survived','mean')).reset_index()

   Pclass  survived_mean
0       1       0.629630
1       2       0.472826
2       3       0.242363

In [114]:
# 4. Выведите самое популярное мужское и самое популярное женское имя на корабле - 1 балл

# Достаем имя, первое слово после точки
df['first_name'] = df['Name'].apply(lambda name: name.replace('(','').replace(')','')\
                                                .split('.')[1].split()[0].strip())

df_names = df.groupby(['Sex','first_name']).agg(cnt_names = ('first_name','count')).reset_index()
print('Самое популярное женское имя:', df_names[df_names.Sex == 'female'].sort_values('cnt_names',ascending=False).head(1).first_name.values[0])

print('Самое популярное мужское имя:', df_names[df_names.Sex == 'male'].sort_values('cnt_names',ascending=False).head(1).first_name.values[0])

Самое популярное женское имя: William
Самое популярное мужское имя: William

In [115]:
# 5.Выведите самое популярное мужское и самое популярное женское имя на корабле в каждом классе - 2 балла
df_names = df.groupby(['Sex','first_name','Pclass']).agg(cnt_names = ('first_name','count')).reset_index()

f_1 = df_names[(df_names.Pclass == 1) & (df_names.Sex == 'female')].sort_values('cnt_names',ascending=False).head(1).first_name.values[0]
m_1 = df_names[(df_names.Pclass == 1) & (df_names.Sex == 'male')].sort_values('cnt_names',ascending=False).head(1).first_name.values[0]
f_2 = df_names[(df_names.Pclass == 2) & (df_names.Sex == 'female')].sort_values('cnt_names',ascending=False).head(1).first_name.values[0]
m_2 = df_names[(df_names.Pclass == 2) & (df_names.Sex == 'male')].sort_values('cnt_names',ascending=False).head(1).first_name.values[0]
f_3 = df_names[(df_names.Pclass == 3) & (df_names.Sex == 'female')].sort_values('cnt_names',ascending=False).head(1).first_name.values[0]
m_3 = df_names[(df_names.Pclass == 3) & (df_names.Sex == 'male')].sort_values('cnt_names',ascending=False).head(1).first_name.values[0]

print('Самые популярные имена:')
print(f'1 класс: Мужчины - {m_1}, Женщины - {f_1}')
print(f'2 класс: Мужчины - {m_2}, Женщины - {f_2}')
print(f'3 класс: Мужчины - {m_3}, Женщины - {f_3}')

Самые популярные имена:
1 класс: Мужчины - William, Женщины - William
2 класс: Мужчины - William, Женщины - William
3 класс: Мужчины - William, Женщины - Anna

In [116]:
# 6.Выведите часть таблицы с пассажирами, возраст которых больше 44 лет - 1 балл
df[df.Age > 44].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,first_name
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Timothy
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Elizabeth
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,Mary
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S,Edward
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,Henry

In [117]:
# Выведите часть таблицы с пассажирами, возраст которых меньше 44 лет и которые мужского пола - 2 балла
df[(df.Age < 44) & (df.Sex == 'male')].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,first_name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S,Owen
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050,NaN,S,William
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S,Gosta
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.050,NaN,S,William
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.275,NaN,S,Anders

In [121]:
# Выведите количества n-местных кабин (в которых было 2, 3, 4, ... человека) - 1 балл
df.groupby('Cabin').agg(type_of_cabin = ('Name','count')).reset_index().type_of_cabin.value_counts().reset_index()

   type_of_cabin  count
0              1    101
1              2     38
2              3      5
3              4      3